simplemooc/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

# Definindo namespace
app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    # Usando a view do próprio Django para Login de usuários (não tem a ver com o ADMIN)
    path('entrar/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # Usando a view do próprio Django para Logout
    path('sair/', LogoutView.as_view(next_page='core:home'), name='logout'),

    path('cadastro/', views.register, name='register'),
    path('cadastro/esqueci', views.password_reset, name='reset'),
    path('cadastro/esqueci/<slug:key>', views.password_reset_confirm, name='reset_confirm'),
    path('editar/usuario', views.edit, name='edit'),
    path('editar/senha/', views.edit_password, name='edit-pass'),
]

simplemooc/courses/urls.py
from django.urls import path

from . import views

# Definindo namespace
app_name = 'courses'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:course_slug>', views.details, name='details'),
    path('<slug:course_slug>/inscricao', views.enrollments, name='enrollments'),
    path('<slug:course_slug>/inscricao/cancelar', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:course_slug>/anuncios', views.announcements, name='announcements'),
    path('<slug:course_slug>/anuncios/<int:announcement_id>', views.show_announcement, name='announcement'),
    path('<slug:course_slug>/aulas', views.lessons, name='lessons'),
    path('<slug:course_slug>/aulas/<int:lesson_id>', views.show_lesson, name='show_lesson'),
    path('<slug:course_slug>/material/<int:material_id>', views.material, name='material'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
]

# Se estiver no modo DEBUG, força o django a servir as URLs de imagens estáticas
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):
    # ## Campos customizados
    # Nome de usuário. Precisa ser único. Este campo tem validação de valores. Só são válidos os chars indicados
    username = models.CharField(
        'Nome de Usuário',
        max_length=30,
        unique=True,
        validators=[validators.RegexValidator(
            re.compile(r'^[\w.@+_-]+$'),
            'O nome de usuário só pode conter letras, números ou @.+_-',
            'invalid'
        )]
    )
    # O email é um campo único
    email = models.EmailField('E-mail', unique=True)
    # Não obrigatório
    name = models.CharField('Nome', max_length=100, blank=True)

    # ## Campos necessários para o funcionamento de User
    # Não é obrigatório, mas terá como valor padrão True
    is_active = models.BooleanField('Está Ativo?', blank=True, default=True)
    # Se é da área administrativa
    is_staff = models.BooleanField('É Admin?', blank=True, default=False)
    # Campo atualizado automaticamente no INSERT
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    # Manager do User
    objects = UserManager()

    # Campo único e referencia na hora do login
    USERNAME_FIELD = 'username'
    # Campos obrigatórios para superusuário
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        """
        Descrição curta do nome
        """
        return self.username

    def get_full_name(self):
        """
        Descrição completa do nome. Retorna a representação string deste objeto
        """
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class PasswordReset(models.Model):
    """
    Classe para gerar uma nova senha aleatória quando o usuário esqueceu a senha
    """
    # Chave estrangeira. O pai é o User.id (ou User.pk). Normalmente, basta informar o model. Mas aqui,
    # por se tratar de uma herança do Django, há a necessidade de usar a chave criada em settings
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Usuário',
        on_delete=models.CASCADE,
        # Serve pra indicar qual o nome do objeto para se trazer todos os PasswordsResets do usuário.
        # Se não for indicado, o objeto será sempre '<nomedomodel>_set'
        # Exemplo: resets = user.resets.all()
        related_name='resets'
    )
    key = models.CharField('Chave', max_length=100, unique=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)

    def __str__(self):
        return f'{self.user} em {self.created_at}'

    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        # Ordenando de modo decrescente pela data
        ordering = ['-created_at']

simplemooc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .form import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset

# Isso se faz necessário porque o User é customizado. Isso fará o Django pegar o model criado
User = get_user_model()


def register(request):
    """
    View para cadastro de novo usuário
    """
    # Verificando postagem
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        # Salva os dados do form
        user = form.save()

        # Logando o usuário automaticamente
        user = authenticate(
            username=user.username,
            password=form.cleaned_data['password1']
        )
        login(request, user)

        # Redireciona para tela inicial
        return redirect('core:home')

    return render(request, 'accounts/register.html', {'form': form})


def password_reset(request):
    """
    View para gerar nova senha, quando o usuário a esqueceu
    """
    context = {}

    # Se houve POST, informa, senão cria um form vazio
    form = PasswordResetForm(request.POST or None)
    # Teve postagem, e o fomulário está valido?
    if form.is_valid():
        # Gera uma nova senha
        form.save()
        context['success'] = True

    context['form'] = form

    return render(request, 'accounts/password_reset.html', context)


def password_reset_confirm(request, key):
    """
    View de confirmação de nova senha
    :param request:
    :param key: Chave para se localizar a senha nova
    """
    context = {}
    # Localiza usuário conforme chave passada. Se não encontrar, devolve 404
    reset = get_object_or_404(PasswordReset, key=key)
    # Formulário padrão do Django para reset de senha, passando o usuário localizado em reset
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True

    context['form'] = form
    return render(request, 'accounts/password_reset_confirm.html', context)


# Decorador para verificar se está logado antes de executar a view
@login_required
def dashboard(request):
    """
    View após logado
    """
    return render(request, 'accounts/dashboard.html')


@login_required
def edit(request):
    """
    Editando usuário
    """
    context = {}

    # Houve postagem?
    form = EditAccountForm(request.POST or None, instance=request.user)
    if form.is_valid():
        # Salva o formulário e marca como OK
        form.save()
        messages.success(request, 'Os dados foram alterados com sucesso!')
        return redirect('accounts:dashboard')

    context['form'] = form
    return render(request, 'accounts/dashboard/edit.html', context)


@login_required
def edit_password(request):
    """
    Alteração de senha
    """
    context = {}

    # Teve postagem?
    form = PasswordChangeForm(data=request.POST or None, user=request.user)
    if form.is_valid():
        form.save()
        messages.success(request, 'A senha foi alterada com sucesso!')
        return redirect('accounts:dashboard')

    context['form'] = form
    return render(request, 'accounts/dashboard/edit-pass.html', context)

templates/accounts/dashboard.html
{% extends 'template.html' %}

{# abrindo a base de tags de cursos #}
{% load courses_tags %}

{% block title %}Painel{% endblock %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <ul class="breadcrumb">

                {% block breadcrumb %}
                    <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
                {% endblock %}

            </ul>
        </div>
        <div class="pure-u-1-3">
            <div class="pure-menu pure-menu-open">
                <ul>
                    <li class="pure-menu-heading">
                        Bem-vindo, {{ user }}
                    </li>
                    {% my_courses user as enrollments %}
                    {% block menu_options %}
                        <li class="pure-menu-heading"><b>Cursos</b></li>
                        {# usando a tag criada em courses_tags.py #}
                        {% for enrollment in enrollments %}
                            <li>
                                <a href="{% url 'courses:announcements' enrollment.course.slug %}">
                                    <i class="fa fa-book"></i>
                                    {{ enrollment.course }}
                                </a>
                            </li>
                        {% empty %}
                            <li>Nenhum curso encontrado</li>
                        {% endfor %}
                        <li class="pure-menu-heading"><b>Configurações de Conta</b></li>
                        <li>
                            <a href="{% url 'accounts:edit' %}">
                                <i class="fa fa-cog"></i>
                                Editar Conta
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:edit-pass' %}">
                                <i class="fa fa-lock"></i>
                                Editar Senha
                            </a>
                        </li>
                    {% endblock %}
                </ul>
            </div>
        </div>
        <div class="pure-u-2-3">
            <div class="inner">
                {% block dashboard_content %}
                    <h2>Meus Cursos</h2>
                    {% for enrollment in enrollments %}
                        <div class="well">
                            <h3>
                                {{ enrollment.course }}
                                <small>({{ enrollment.course.start_date|date:'d/m/Y'|default:'Não informado' }})</small>
                            </h3>
                            {{ enrollment.course.description|linebreaks }}
                            <div class="pure-controls">
                                <a href="{% url 'courses:announcements' enrollment.course.slug %}"
                                   class="pure-button pure-button-primary">Acessar</a>
                                <a href="{% url 'courses:undo_enrollment' enrollment.course.slug %}"
                                   class="pure-button button-error">Cancelar</a>
                            </div>
                        </div>
                    {% empty %}
                        <aside class="pure-u-1">
                            <p>Nenhum curso inscrito</p>
                        </aside>
                    {% endfor %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/login.html
{% extends 'template.html' %}
{% block title %}Login{% endblock %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe seus dados de cadastro</h2>
            <form class="pure-form pure-form-stacked" action="" method="post">

                {% csrf_token %}

                <fieldset>
                    <!-- Erros não relacionados aos campos, como, por exemplo, senha inválida -->
                    {{ form.non_field_errors }}

                    {% for field in form %}

                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>

                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                    </div>
                </fieldset>
                <p>
                    Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br/>
                    Esqueceu a senha? <a href="{% url 'accounts:reset' %}" title="">Nova senha</a> <br/>
                </p>
            </form>
        </div>
    </div>
{% endblock %}

templates/accounts/password_reset.html
{% extends 'template.html' %}
{% block title %}Esqueci Minha Senha{% endblock %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            {% if success %}
                <p>Um email foi enviado para você com mais detalhes de como criar uma nova senha</p>
            {% else %}
                <h2>Informe seu E-mail</h2>
                <form class="pure-form pure-form-stacked" action="" method="post">

                    {% csrf_token %}

                    <fieldset>
                        <!-- Erros não relacionados aos campos, como, por exemplo, senha inválida -->
                        {{ form.non_field_errors }}

                        {% for field in form %}

                            <div class="pure-control-group">
                                {{ field.label_tag }}
                                {{ field }}
                                {{ field.errors }}
                            </div>

                        {% endfor %}

                        <div class="pure-controls">
                            <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
                        </div>
                    </fieldset>

                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'template.html' %}
{% block title %}Esqueci Minha Senha{% endblock %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            {% if success %}
                <p>Sua senha foi alterada com sucesso</p>
            {% else %}
                <h2>Informe uma nova Senha</h2>
                <form class="pure-form pure-form-stacked" action="" method="post">

                    {% csrf_token %}

                    <fieldset>
                        <!-- Erros não relacionados aos campos, como, por exemplo, senha inválida -->
                        {{ form.non_field_errors }}

                        {% for field in form %}

                            <div class="pure-control-group">
                                {{ field.label_tag }}
                                {{ field }}
                                {{ field.errors }}
                            </div>

                        {% endfor %}

                        <div class="pure-controls">
                            <button type="submit" class="pure-button pure-button-primary">Salvar</button>
                        </div>
                    </fieldset>

                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/accounts/password_reset_mail.html
<p>
    Para criar uma nova senha, click
    <a href="http://localhost:8000{% url 'accounts:reset_confirm' reset.key %}"
       title="Link para criar nova senha">aqui</a>
</p>

templates/accounts/register.html
{% extends 'template.html' %}
{% block title %}Cadastro{% endblock %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe seus dados para cadastro</h2>
            <form class="pure-form pure-form-stacked" action="" method="post">

                {% csrf_token %}

                <fieldset>
                    <!-- Erros não relacionados aos campos, como, por exemplo, senha inválida -->
                    {{ form.non_field_errors }}

                    {% for field in form %}

                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>

                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                    </div>
                </fieldset>
            
            </form>
        </div>
    </div>
{% endblock %}