simplemooc/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

# Definindo namespace
app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    # Usando a view do próprio Django para Login de usuários (não tem a ver com o ADMIN)
    path('entrar/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # Usando a view do próprio Django para Logout
    path('sair/', LogoutView.as_view(next_page='core:home'), name='logout'),

    path('cadastro/', views.register, name='register'),
    path('cadastro/esqueci', views.password_reset, name='reset'),
    path('cadastro/esqueci/<slug:key>', views.password_reset_confirm, name='reset_confirm'),
    path('editar/usuario', views.edit, name='edit'),
    path('editar/senha/', views.edit_password, name='edit-pass'),
]

simplemooc/core/urls.py
from django.urls import path

from . import views

# Definindo namespace
app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('contato/', views.contact, name='contact'),
]

simplemooc/courses/urls.py
from django.urls import path

from . import views

# Definindo namespace
app_name = 'courses'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:course_slug>', views.details, name='details'),
    path('<slug:course_slug>/inscricao', views.enrollments, name='enrollments'),
    path('<slug:course_slug>/inscricao/cancelar', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:course_slug>/anuncios', views.announcements, name='announcements'),
    path('<slug:course_slug>/anuncios/<int:announcement_id>', views.show_announcement, name='announcement'),
    path('<slug:course_slug>/aulas', views.lessons, name='lessons'),
    path('<slug:course_slug>/aulas/<int:lesson_id>', views.show_lesson, name='show_lesson'),
    path('<slug:course_slug>/material/<int:material_id>', views.material, name='material'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
]

# Se estiver no modo DEBUG, força o django a servir as URLs de imagens estáticas
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/template.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância"/>
    <title>Simple MOOC | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>
<body>
<div class="header">
    <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">SIMPLE MOOC</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'courses:index' %}">Cursos</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>

            <!-- Verifica se o usuário está logado -->
            {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:dashboard' %}">Painel</a></li>
                <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
            {% else %}
                <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
            {% endif %}

        </ul>
    </div>
</div>
<div class="content">
    {% if messages %}
        <div class="pure-g-r content-ribbon">
            {% for message in messages %}
                <aside class="pure-u-1 message {% if message.tags %}{{ message.tags }}{% endif %}">
                    <p>{{ message }}</p>
                </aside>
            {% endfor %}
        </div>
    {% endif %}

    {% block content %}{% endblock %}

    <div class="footer">
        Simple MOOC - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>