simplemooc/courses/urls.py
from django.urls import path

from . import views

# Definindo namespace
app_name = 'courses'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:course_slug>', views.details, name='details'),
    path('<slug:course_slug>/inscricao', views.enrollments, name='enrollments'),
    path('<slug:course_slug>/inscricao/cancelar', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:course_slug>/anuncios', views.announcements, name='announcements'),
    path('<slug:course_slug>/anuncios/<int:announcement_id>', views.show_announcement, name='announcement'),
    path('<slug:course_slug>/aulas', views.lessons, name='lessons'),
    path('<slug:course_slug>/aulas/<int:lesson_id>', views.show_lesson, name='show_lesson'),
    path('<slug:course_slug>/material/<int:material_id>', views.material, name='material'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
]

# Se estiver no modo DEBUG, força o django a servir as URLs de imagens estáticas
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/courses/forms.py
from django import forms
from django.conf import settings

from simplemooc.core.mail import send_mail_template
from .models import Comment


class ContactCourse(forms.Form):
    """
    Classe para Formulário de Contato

    Sempre use dentro da tag <form>:
        {% csrf_token %}

    Para renderizar, no template use:
        {{ form }}              apenas os campos
        {{ form.as_p }}         campos dentro de paragrafos
        {{ form.as_table }}     campos dentro de uma tabela (Ele não adiciona a tag <table>)
    Para campos personalizados, faça:
        {% for field in form }%
            {{ field.label_tag }} (ou {{ field.label }} se quiser apenas o texto do label)
            {{ field }}
            # Imprima apenas {{ field.errors }} ou, se quiser personalizar faça:
            {% if field.errors %}
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            {% endif %}
        {% endfor %}
    """
    # Campo Nome
    name = forms.CharField(label='Nome', max_length=100, required=False)
    # Campo Email
    email = forms.EmailField(label='E-mail')
    # Campo Mensagem. Não existe o tipo TextField. Ao invés, use o widget
    message = forms.CharField(label='Mensagem/Dúvida', widget=forms.Textarea)

    def send_mail(self, course):
        """
        Definindo envio de email
        """
        subject = f'[{course}] | Contato'

        # Enviando email usando template (criado em core/mail.py)
        send_mail_template(
            subject,
            'courses/contact_email.html',
            self.cleaned_data,
            [settings.CONTACT_EMAIL]
        )


class CommentForm(forms.ModelForm):
    class Meta:
        # Qual o modelo a ser usado?
        model = Comment
        # Quais campos devem ser exibidos?
        fields = ['comment']

simplemooc/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Course, Enrollment, Lesson, Material
from .forms import ContactCourse, CommentForm
from .decorators import enrollment_required


def index(request):
    # Pegando todos os cursos
    cursos = Course.objects.all()
    return render(request, 'courses/index.html', {
        'courses': cursos
    })


def details(request, course_slug):
    # Esse método funciona, mas pode retornar erro se o ID não existir.
    # curso = Course.objects.get(pk=course_id)  # ou slug=<variavel_slug>

    # O ideal é usar assim, para direcionar à pagina 404 se o objeto não existir:
    curso = get_object_or_404(Course, slug=course_slug)  # ou pk=<variavel_id>
    contexto = {}

    # Houve postagem e Formulário é válido?
    form = ContactCourse(request.POST or None)
    if form.is_valid():
        # Adiciona uma tag ao contexto
        contexto['is_valid'] = True
        # Se precisar acessar os dados validados do formulário, eles estarão no dicionário:
        # form.cleaned_data

        # Envia email e limpa o formulário por estar válido
        form.send_mail(curso)
        form = ContactCourse()

    contexto['form'] = form
    contexto['course'] = curso

    return render(request, 'courses/detalhe.html', contexto)


@login_required
def enrollments(request, course_slug):
    """
    View para inscrições
    :param request:
    :param course_slug: slug do curso a ser adicionado
    """
    course = get_object_or_404(Course, slug=course_slug)
    # Pega uma associação ou cria automaticamente para usuário/curso. O segundo parametro é se criou ou não (bool)
    enrollment, created = Enrollment.objects.get_or_create(user=request.user, course=course)
    # Precisou criar?
    if created:
        enrollment.active()
        messages.success(request, 'Você foi inscrito no curso com sucesso :)')
    else:
        messages.info(request, 'Você já está inscrito neste curso ;)')

    return redirect('accounts:dashboard')


@login_required
def undo_enrollment(request, course_slug):
    # Pegando curso
    course = get_object_or_404(Course, slug=course_slug)
    # Pegando inscrição
    enrollment = get_object_or_404(Enrollment, course=course, user=request.user)

    # Confirmou remoção da inscrição?
    if request.method == 'POST':
        enrollment.delete()
        messages.success(request, 'Sua inscrição foi cancelada com sucesso!')
        return redirect('accounts:dashboard')

    return render(request, 'courses/dashboard/undo_enrollment.html', {
        'course': course
    })


@login_required
@enrollment_required
def announcements(request, course_slug):
    """
    View para anuncios do curso no dashboard
    """
    # Pegando curso (no decorador)
    course = request.course

    return render(request, 'courses/dashboard/announcements.html', {
        'course': course,
        'announcements': course.announcements.all()
    })


@login_required
@enrollment_required
def show_announcement(request, course_slug, announcement_id):
    # Pegando curso (no decorador)
    course = request.course
    # Pegando anúncio
    announcement = get_object_or_404(course.announcements.all(), pk=announcement_id)

    # Teve postage,?
    form = CommentForm(request.POST or None)
    if form.is_valid():
        # Cria o objeto, mas não salva
        comment = form.save(commit=False)
        # Preenche os campos que faltam
        comment.user = request.user
        comment.announcement = announcement
        # Agora sim, salvando!
        comment.save()
        form = CommentForm()
        messages.success(request, 'Seu comentário foi postado!')

    return render(request, 'courses/dashboard/show_announcement.html', {
        'course': course,
        'announcement': announcement,
        'form': form
    })


@login_required
@enrollment_required
def lessons(request, course_slug):
    # Pegando curso (no decorador)
    course = request.course
    return render(request, 'courses/dashboard/lessons.html', {
        'course': course,
        # Chama todas as aulas se for admin, ou apenas as liberadas, caso contrário
        'lessons': course.lessons.all() if request.user.is_staff else course.release_lessons()
    })


@login_required
@enrollment_required
def show_lesson(request, course_slug, lesson_id):
    # Pegando curso (no decorador)
    course = request.course
    # Pega a aula, garantindo que ID informado pertence ao curso informado
    lesson = get_object_or_404(Lesson, pk=lesson_id, course=course)
    # Se não for admin, verifica se a aula está disponível
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Essa aula ainda não está disponível')
        return redirect('accounts:dashboard')

    return render(request, 'courses/dashboard/show_lesson.html', {
        'course': course,
        'lesson': lesson
    })


@login_required
@enrollment_required
def material(request, course_slug, material_id):
    # Pegando curso (no decorador)
    course = request.course
    # Pega o material, garantindo que ID informado pertence ao curso informado da aula informado
    this_material = get_object_or_404(Material, pk=material_id, lesson__course=course)
    # Se não for admin, verifica se a aula está disponível
    if not request.user.is_staff and not this_material.lesson.is_available():
        messages.error(request, 'Essa aula ainda não está disponível, e nem os materiais dela')
        return redirect('accounts:dashboard')
    # Verifica se é embedded. Se não redireciona
    if not this_material.is_embedded():
        return redirect(this_material.file.url)

    return render(request, 'courses/dashboard/material.html', {
        'course': course,
        'lesson': this_material.lesson,
        'material': this_material
    })

templates/courses/announcements.html
{% extends 'accounts/dashboard.html' %}

{% block title %}{{ block.super }} - Anúncios{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:announcements' course.slug %}">Anúncio de {{ course }}</a></li>
{% endblock %}

{% block menu_options %}
    <li class="pure-menu-heading">
        {{ course }}
    </li>
    <li>
        <a href="#">
            <i class="fa fa-video-camera"></i>
            Aulas e Materiais
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-info-circle"></i>
            Informações
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-envelope"></i>
            Anúncios
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-comments"></i>
            Fórum de Dúvidas
        </a>
    </li>
    {{ block.super }}
{% endblock %}

{% block dashboard_content %}
    <div class="well">
        <h2>Iníco das aulas, sejam bem vindos</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <p>
            <a href="#comments" title="">
                <i class="fa fa-comments-o"></i>
                10 Comentários
            </a>
        </p>
    </div>
{% endblock %}

templates/courses/announcements_mail.html
<strong>{{ announcement }}</strong>
{{ announcement.content|linebreaks }}

templates/courses/contact_email.html
<p><strong>Nome:</strong> {{ name }}</p>
<p><strong>E-mail:</strong> {{ email }}</p>
{{ message|linebreaks }}

templates/courses/dashboard.html
{% extends 'accounts/dashboard.html' %}

{% block title %}{{ block.super }} - {{ course }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:announcements' course.slug %}">{{ course }}</a></li>
{% endblock %}

{% block menu_options %}
    <li class="pure-menu-heading">
        {{ course }}
    </li>
    <li>
        <a href="{% url 'courses:lessons' course.slug %}">
            <i class="fa fa-video-camera"></i>
            Aulas e Materiais
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-info-circle"></i>
            Informações
        </a>
    </li>
    <li>
        <a href="{% url 'courses:announcements' course.slug %}">
            <i class="fa fa-envelope"></i>
            Anúncios
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-comments"></i>
            Fórum de Dúvidas
        </a>
    </li>
    {{ block.super }}
{% endblock %}

templates/courses/detalhe.html
{% extends 'template.html' %}
{% load static %}
{% block title %}Curso{% endblock %}

{% block content %}

    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        {{ course }}
                    </h1>
                    <h2 class="splash-subhead">
                        {{ course.description }}
                    </h2>
                    <p>
                        <a href="{% url 'courses:enrollments' course.slug %}" class="pure-button primary-button">Inscreva-se</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="pure-g-r content-ribbon">
        <div class="pure-u-2-3">
            <div class="l-box">
                <h4 class="content-subhead">Sobre o Curso</h4>
                <p>{{ course.about | linebreaks }}</p>
            </div>
        </div>
        <div class="pure-u-1-3">
            <div class="l-box">
                {% if course.image %}
                    <img src="{{ course.image.url }}" alt="{{ course }}">
                {% else %}
                    <img src="{% static 'img/course-image.png' %}" alt="Sem Imagem">
                {% endif %}
                <h4>Dúvidas?</h4>
                <p>
                    <a href="#contato" title="" class="pure-button">Fale Conosco</a>
                </p>
            </div>
        </div>
    </div>

    <div class="pure-g-r content-ribbon" id="contato">
        <div class="pure-u-1">
            <h3>Tire sua dúvida sobre o Curso</h3>
            {% if is_valid %}
                <p>Você enviou o formulário com sucesso!</p>
            {% endif %}
            <form class="pure-form pure-form-aligned" method="post" action="#contato">
                {% csrf_token %}
                <fieldset>

                    {% for field in form %}

                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.errors %}
                                <ul class="errorlist">
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>

                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock %}

templates/courses/index.html
{% extends 'template.html' %}
{% load static %}
{% block title %}Cursos{% endblock %}

{% block content %}

    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <div class="l-box">
                <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
                <p>Abaixo a lista de cursos disponíveis na plataforma</p>
            </div>
        </div>
    </div>

    {% for course in courses %}

        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <a href="{% url 'courses:details' course.slug %}">
                        {% if course.image %}
                            <img src="{{ course.image.url }}" alt="{{ course }}">
                        {% else %}
                            <img src="{% static 'img/course-image.png' %}" alt="Sem Imagem">
                        {% endif %}
                    </a>
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course }}</a></h4>
                    {{ course.about | linebreaks }}
                </div>
            </div>
        </div>

    {% empty %}

        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1">
                <div class="l-box">
                    <p>Nenhum curso está disponível na plataforma</p>
                </div>
            </div>
        </div>

    {% endfor %}

{% endblock %}