simplemooc/courses/urls.py
from django.urls import path

from . import views

# Definindo namespace
app_name = 'courses'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:course_slug>', views.details, name='details'),
    path('<slug:course_slug>/inscricao', views.enrollments, name='enrollments'),
    path('<slug:course_slug>/inscricao/cancelar', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:course_slug>/anuncios', views.announcements, name='announcements'),
    path('<slug:course_slug>/anuncios/<int:announcement_id>', views.show_announcement, name='announcement'),
    path('<slug:course_slug>/aulas', views.lessons, name='lessons'),
    path('<slug:course_slug>/aulas/<int:lesson_id>', views.show_lesson, name='show_lesson'),
    path('<slug:course_slug>/material/<int:material_id>', views.material, name='material'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
]

# Se estiver no modo DEBUG, força o django a servir as URLs de imagens estáticas
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/courses/forms.py
from django import forms
from django.conf import settings

from simplemooc.core.mail import send_mail_template
from .models import Comment


class ContactCourse(forms.Form):
    """
    Classe para Formulário de Contato

    Sempre use dentro da tag <form>:
        {% csrf_token %}

    Para renderizar, no template use:
        {{ form }}              apenas os campos
        {{ form.as_p }}         campos dentro de paragrafos
        {{ form.as_table }}     campos dentro de uma tabela (Ele não adiciona a tag <table>)
    Para campos personalizados, faça:
        {% for field in form }%
            {{ field.label_tag }} (ou {{ field.label }} se quiser apenas o texto do label)
            {{ field }}
            # Imprima apenas {{ field.errors }} ou, se quiser personalizar faça:
            {% if field.errors %}
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            {% endif %}
        {% endfor %}
    """
    # Campo Nome
    name = forms.CharField(label='Nome', max_length=100, required=False)
    # Campo Email
    email = forms.EmailField(label='E-mail')
    # Campo Mensagem. Não existe o tipo TextField. Ao invés, use o widget
    message = forms.CharField(label='Mensagem/Dúvida', widget=forms.Textarea)

    def send_mail(self, course):
        """
        Definindo envio de email
        """
        subject = f'[{course}] | Contato'

        # Enviando email usando template (criado em core/mail.py)
        send_mail_template(
            subject,
            'courses/contact_email.html',
            self.cleaned_data,
            [settings.CONTACT_EMAIL]
        )


class CommentForm(forms.ModelForm):
    class Meta:
        # Qual o modelo a ser usado?
        model = Comment
        # Quais campos devem ser exibidos?
        fields = ['comment']

simplemooc/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Course, Enrollment, Lesson, Material
from .forms import ContactCourse, CommentForm
from .decorators import enrollment_required


def index(request):
    # Pegando todos os cursos
    cursos = Course.objects.all()
    return render(request, 'courses/index.html', {
        'courses': cursos
    })


def details(request, course_slug):
    # Esse método funciona, mas pode retornar erro se o ID não existir.
    # curso = Course.objects.get(pk=course_id)  # ou slug=<variavel_slug>

    # O ideal é usar assim, para direcionar à pagina 404 se o objeto não existir:
    curso = get_object_or_404(Course, slug=course_slug)  # ou pk=<variavel_id>
    contexto = {}

    # Houve postagem e Formulário é válido?
    form = ContactCourse(request.POST or None)
    if form.is_valid():
        # Adiciona uma tag ao contexto
        contexto['is_valid'] = True
        # Se precisar acessar os dados validados do formulário, eles estarão no dicionário:
        # form.cleaned_data

        # Envia email e limpa o formulário por estar válido
        form.send_mail(curso)
        form = ContactCourse()

    contexto['form'] = form
    contexto['course'] = curso

    return render(request, 'courses/detalhe.html', contexto)


@login_required
def enrollments(request, course_slug):
    """
    View para inscrições
    :param request:
    :param course_slug: slug do curso a ser adicionado
    """
    course = get_object_or_404(Course, slug=course_slug)
    # Pega uma associação ou cria automaticamente para usuário/curso. O segundo parametro é se criou ou não (bool)
    enrollment, created = Enrollment.objects.get_or_create(user=request.user, course=course)
    # Precisou criar?
    if created:
        enrollment.active()
        messages.success(request, 'Você foi inscrito no curso com sucesso :)')
    else:
        messages.info(request, 'Você já está inscrito neste curso ;)')

    return redirect('accounts:dashboard')


@login_required
def undo_enrollment(request, course_slug):
    # Pegando curso
    course = get_object_or_404(Course, slug=course_slug)
    # Pegando inscrição
    enrollment = get_object_or_404(Enrollment, course=course, user=request.user)

    # Confirmou remoção da inscrição?
    if request.method == 'POST':
        enrollment.delete()
        messages.success(request, 'Sua inscrição foi cancelada com sucesso!')
        return redirect('accounts:dashboard')

    return render(request, 'courses/dashboard/undo_enrollment.html', {
        'course': course
    })


@login_required
@enrollment_required
def announcements(request, course_slug):
    """
    View para anuncios do curso no dashboard
    """
    # Pegando curso (no decorador)
    course = request.course

    return render(request, 'courses/dashboard/announcements.html', {
        'course': course,
        'announcements': course.announcements.all()
    })


@login_required
@enrollment_required
def show_announcement(request, course_slug, announcement_id):
    # Pegando curso (no decorador)
    course = request.course
    # Pegando anúncio
    announcement = get_object_or_404(course.announcements.all(), pk=announcement_id)

    # Teve postage,?
    form = CommentForm(request.POST or None)
    if form.is_valid():
        # Cria o objeto, mas não salva
        comment = form.save(commit=False)
        # Preenche os campos que faltam
        comment.user = request.user
        comment.announcement = announcement
        # Agora sim, salvando!
        comment.save()
        form = CommentForm()
        messages.success(request, 'Seu comentário foi postado!')

    return render(request, 'courses/dashboard/show_announcement.html', {
        'course': course,
        'announcement': announcement,
        'form': form
    })


@login_required
@enrollment_required
def lessons(request, course_slug):
    # Pegando curso (no decorador)
    course = request.course
    return render(request, 'courses/dashboard/lessons.html', {
        'course': course,
        # Chama todas as aulas se for admin, ou apenas as liberadas, caso contrário
        'lessons': course.lessons.all() if request.user.is_staff else course.release_lessons()
    })


@login_required
@enrollment_required
def show_lesson(request, course_slug, lesson_id):
    # Pegando curso (no decorador)
    course = request.course
    # Pega a aula, garantindo que ID informado pertence ao curso informado
    lesson = get_object_or_404(Lesson, pk=lesson_id, course=course)
    # Se não for admin, verifica se a aula está disponível
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Essa aula ainda não está disponível')
        return redirect('accounts:dashboard')

    return render(request, 'courses/dashboard/show_lesson.html', {
        'course': course,
        'lesson': lesson
    })


@login_required
@enrollment_required
def material(request, course_slug, material_id):
    # Pegando curso (no decorador)
    course = request.course
    # Pega o material, garantindo que ID informado pertence ao curso informado da aula informado
    this_material = get_object_or_404(Material, pk=material_id, lesson__course=course)
    # Se não for admin, verifica se a aula está disponível
    if not request.user.is_staff and not this_material.lesson.is_available():
        messages.error(request, 'Essa aula ainda não está disponível, e nem os materiais dela')
        return redirect('accounts:dashboard')
    # Verifica se é embedded. Se não redireciona
    if not this_material.is_embedded():
        return redirect(this_material.file.url)

    return render(request, 'courses/dashboard/material.html', {
        'course': course,
        'lesson': this_material.lesson,
        'material': this_material
    })

templates/courses/dashboard/announcements.html
{% extends 'courses/dashboard.html' %}

{% block title %}{{ block.super }} - Anúncios{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:announcements' course.slug %}">Anúncios</a></li>
{% endblock %}


{% block dashboard_content %}
    {% for announcement in announcements %}
        <div class="well">
            <h2><a href="{% url 'courses:announcement' course.slug announcement.pk %}">{{ announcement.title }}</a></h2>
            {{ announcement.content|linebreaks }}
            <p>
                <a href="{% url 'courses:announcement' course.slug announcement.pk %}#comments" title="">
                    <i class="fa fa-comments-o"></i>
                    {% with announcement.comments.count as count %}
                        {{ count }} Comentário{{ count|pluralize }}
                    {% endwith %}
                </a>
            </p>
        </div>
    {% empty %}
        <div class="well">
            <h2>
                Nenhum anúncio criado.
            </h2>
        </div>
    {% endfor %}
{% endblock %}

templates/courses/dashboard/lessons.html
{% extends 'courses/dashboard.html' %}

{% block title %}{{ block.super }} - Aulas{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
{% endblock %}


{% block dashboard_content %}
    {% for lesson in lessons %}
        <div class="well">
            <h2><a href="{% url 'courses:show_lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
            <p>
                {# truncatewords coloca apenas o número de palavras informadas e depois põe ... #}
                {{ lesson.description|truncatewords:50|linebreaksbr }}
                <br/>
                <br/>
                <a href="{% url 'courses:show_lesson' course.slug lesson.pk %}" title="">
                    <i class="fa fa-eye"></i>
                    Acessar Aula
                </a>
            </p>
        </div>
    {% empty %}
        <div class="well">
            <h2>
                Nenhuma aula disponível.
            </h2>
        </div>

    {% endfor %}
{% endblock %}

templates/courses/dashboard/material.html
{% extends 'courses/dashboard.html' %}

{% block title %}{{ block.super }} - Aulas{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:show_lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></li>
{% endblock %}


{% block dashboard_content %}
    <div class="well">
        <h2>{{ material }}</h2>
        {{ material.embedded|safe }}
        <p>
            <a href="{% url 'courses:show_lesson' course.slug material.lesson.pk %}">Voltar</a>
        </p>
    </div>
{% endblock %}

templates/courses/dashboard/show_announcement.html
{% extends 'courses/dashboard.html' %}

{% block title %}{{ block.super }} - Anúncios{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:announcements' course.slug %}">{{ announcement }}</a></li>
{% endblock %}


{% block dashboard_content %}
    <div class="well">
        <h2>{{ announcement }}</h2>
        {{ announcement.content|linebreaks }}
    </div>
    <div class="well">
        <h4 id="comments">Comentários <a class="fright" href="#add_comment">Comentar</a></h4>

        {% for comment in announcement.comments.all %}
            <hr/>
            <p>
                <strong>{{ comment.user }}</strong> disse à {{ comment.created_at|timesince }} atrás: <br/>
                {{ comment|linebreaksbr }}
            </p>
        {% empty %}
            <p>
                Nenhum comentário para este anúncio
            </p>
        {% endfor %}

        <hr>
        <form method="post" class="pure-form pure-form-stacked" id="add_comment">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="pure-control-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

templates/courses/dashboard/show_lesson.html
{% extends 'courses/dashboard.html' %}

{% block title %}{{ block.super }} - Aulas{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:show_lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock %}


{% block dashboard_content %}
    <div class="well">
        <h2>{{ lesson }}</h2>
        {{ lesson.description|linebreaks }}
        {% if lesson.materials %}
            <h4>Material da Aula</h4>
            <table class="pure-table full">
                <thead>
                <tr>
                    <th>
                        Nome
                    </th>
                    <th>
                        Ação
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for material in lesson.materials.all %}
                    {# cycle define um ciclo, trocando entre cada argumento a cada passada no for #}
                    {# https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#cycle #}
                    <tr class="{% cycle '' 'pure-table-odd' %}">
                        <td>
                            {{ material }}
                        </td>
                        <td>
                            {% if material.is_embedded %}
                                <a href="{% url 'courses:material' course.slug material.pk %}">
                                    <i class="fa fa-video-camera"></i>
                                    Acessar
                                </a>
                            {% else %}
                                <a href="{{ material.file.url }}" target="_blank">
                                    <i class="fa fa-download"></i>
                                    Baixar
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock %}

templates/courses/dashboard/undo_enrollment.html
{% extends 'courses/dashboard.html' %}

{% block title %}{{ block.super }} - Anúncios{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:undo_enrollment' course.slug %}">
        Cancelar Inscrição
    </a></li>
{% endblock %}

{% block dashboard_content %}
    <form method="post">
        {% csrf_token %}
        <h3>Você deseja realmente cancelar a inscrição deste curso?</h3>
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Confirmar</button>
            <a href="{% url 'courses:announcements' course.slug %}" class="pure-button">Voltar</a>
        </div>
    </form>
{% endblock %}